# Generated by Django 3.1.7 on 2021-03-29 08:59

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to=account.models.upload_to, verbose_name='Profile Photo'),
        ),
    ]
